---
- name: update web, nfs and db webserver
  hosts: webserver, nfs
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

    - name: create a directory
      file:
        path: /home/sample/ansible.txt
        state: touch

    - name:  set timezone
      timezone:
        name: Europe/Brussels

- name: update db server
  hosts: db
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: create a directory
      file:
        path: /home/sample/ansible.txt
        state: touch

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest

    - name:  set timezone
      timezone:
        name: Europe/Brussels
